#pragma once

#define IDR_PNG_EFI_CHECKER  201
#define IDR_PNG_EMU_CHECKER  202
#define IDR_PNG_WINSCAN      203
#define IDR_PNG_KERNEL_SCAN  204
#define IDR_PNG_GENERAL      205
#define IDR_PNG_SYSMON       206
#define IDR_PNG_DEEP_SCAN    207

#define IDR_DRIVER_XVSCREEN  301
#define IDR_DRIVER_RTCORE64  302
